### ISSUE TITLE
how do I make a offline version of this

### ISSUE THREAD

**Issue by DragonVsKira** [PhilipKyres/BamStats#2]
please and thank you

**Comment by PhilipKyres** [comment]
You would have to clone the repository, compile the code and host it on your own computer or server, with a new local MySQL database. [Here](https://msdn.microsoft.com/en-us/library/58wxa9w5(v=vs.120).aspx) might be a good place to start.

**Comment by DragonVsKira** [comment]
how do i clone the repository

**Comment by PhilipKyres** [comment]
[How to clone a Git repository using visual studio. ](https://docs.microsoft.com/en-us/vsts/git/tutorial/clone?view=vsts&tabs=visual-studio)

If you have no experience with ASP.NET or C# you might have trouble hosting it locally. There are lots of resources and tutorials online but there is a lot to know.
